variables:
IMAGE_VERSION: "1.2.3"

services:
  - docker:dind

stages:
  - build
  - docker-test
  - docker-release
  - deploy-test
  - deploy-release
  # - analysis

build-prod:
  stage: build
  image: node:latest
  script:
    - npm install -g @angular/cli
    - npm install -g ng-tailwindcss
    - npm install
    - npm run build_prod
  artifacts:
    expire_in: 1 hour
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - dist/
  only:
    - master

docker-release:
  stage: docker-release
  image: docker:latest
  before_script:
    - docker login -u $CHB_REGISTRY_UNAME -p $CHB_REGISTRY_PWD https://rancher.saas.chb-technologies.ch:5000
  script:
    - docker build -t "rancher.saas.chb-technologies.ch:5000/arkcash-web-2:$IMAGE_VERSION" .
    - docker tag "rancher.saas.chb-technologies.ch:5000/arkcash-web-2:$IMAGE_VERSION" "rancher.saas.chb-technologies.ch:5000/arkcash-web-2:latest"
    - docker push "rancher.saas.chb-technologies.ch:5000/arkcash-web-2:latest"
    - docker push "rancher.saas.chb-technologies.ch:5000/arkcash-web-2:$IMAGE_VERSION"
  only:
    - master

deploy-test:
  stage: deploy-test
  image: rancher.saas.chb-technologies.ch:5000/rancher2-gitlab-deploy
  script:
    - upgrade --cluster tests-qa --environment Tests --stack arkcash --service arkcash-web --new-image "rancher.saas.chb-technologies.ch:5000/arkcash-web-2:$IMAGE_VERSION"
  only:
    - master

deploy-release:
  stage: deploy-release
  image: rancher.saas.chb-technologies.ch:5000/rancher2-gitlab-deploy
  script:
    - upgrade --cluster prod --environment Default --stack arkcash --service arkcash-web --new-image "rancher.saas.chb-technologies.ch:5000/arkcash-web-2:$IMAGE_VERSION"
  only:
    - release
